import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "lotin" | "kril" | "rus";

const LANG_KEY = "suv-kpi-lang";

/* ─── Kril → Latin transliteratsiya ─── */
const HASC = (s: string) => /[\u0400-\u04FF]/.test(s);

const CYR_MULTI: [string, string][] = [
  ["Ш","Sh"],["ш","sh"],
  ["Ч","Ch"],["ч","ch"],
  ["Ю","Yu"],["ю","yu"],
  ["Я","Ya"],["я","ya"],
  ["Ё","Yo"],["ё","yo"],
  ["Ж","J"], ["ж","j"],
  ["Ғ","G'"],["ғ","g'"],
  ["Ў","O'"],["ў","o'"],
];
const CYR_SINGLE: [string, string][] = [
  ["А","A"],["а","a"],["Б","B"],["б","b"],["В","V"],["в","v"],
  ["Г","G"],["г","g"],["Д","D"],["д","d"],["Е","E"],["е","e"],
  ["З","Z"],["з","z"],["И","I"],["и","i"],["Й","Y"],["й","y"],
  ["К","K"],["к","k"],["Қ","Q"],["қ","q"],["Л","L"],["л","l"],
  ["М","M"],["м","m"],["Н","N"],["н","n"],["О","O"],["о","o"],
  ["П","P"],["п","p"],["Р","R"],["р","r"],["С","S"],["с","s"],
  ["Т","T"],["т","t"],["У","U"],["у","u"],["Ф","F"],["ф","f"],
  ["Х","X"],["х","x"],["Ҳ","H"],["ҳ","h"],["Ц","Ts"],["ц","ts"],
  ["Э","E"],["э","e"],["Ъ","'"],["ъ","'"],["Ь",""],["ь",""],
  ["Ы","I"],["ы","i"],
];

export function cyrToLatin(text: string): string {
  if (!text || !HASC(text)) return text;
  let res = "";
  let i = 0;
  while (i < text.length) {
    let matched = false;
    for (const [from, to] of CYR_MULTI) {
      if (text.startsWith(from, i)) { res += to; i += from.length; matched = true; break; }
    }
    if (!matched) {
      for (const [from, to] of CYR_SINGLE) {
        if (text.startsWith(from, i)) { res += to; i += from.length; matched = true; break; }
      }
    }
    if (!matched) { res += text[i]; i++; }
  }
  return res;
}

/* ─── Latin → Kril transliteratsiya ─── */
const MULTI: [string, string][] = [
  ["SH", "Ш"], ["Sh", "Ш"], ["sh", "ш"],
  ["CH", "Ч"], ["Ch", "Ч"], ["ch", "ч"],
  ["G'", "Ғ"], ["g'", "ғ"],
  ["O'", "Ў"], ["o'", "ў"],
  ["NG", "НГ"], ["Ng", "Нг"], ["ng", "нг"],
  ["YO", "Ё"], ["Yo", "Ё"], ["yo", "ё"],
];
const SINGLE: [string, string][] = [
  ["A","А"],["B","Б"],["D","Д"],["E","Е"],["F","Ф"],
  ["G","Г"],["H","Ҳ"],["I","И"],["J","Ж"],["K","К"],
  ["L","Л"],["M","М"],["N","Н"],["O","О"],["P","П"],
  ["Q","Қ"],["R","Р"],["S","С"],["T","Т"],["U","У"],
  ["V","В"],["W","В"],["X","Х"],["Y","Й"],["Z","З"],
  ["a","а"],["b","б"],["d","д"],["e","е"],["f","ф"],
  ["g","г"],["h","ҳ"],["i","и"],["j","ж"],["k","к"],
  ["l","л"],["m","м"],["n","н"],["o","о"],["p","п"],
  ["q","қ"],["r","р"],["s","с"],["t","т"],["u","у"],
  ["v","в"],["w","в"],["x","х"],["y","й"],["z","з"],
  ["'","ъ"],
];

export function translitToKril(text: string): string {
  let res = "";
  let i = 0;
  while (i < text.length) {
    let matched = false;
    for (const [from, to] of MULTI) {
      if (text.startsWith(from, i)) { res += to; i += from.length; matched = true; break; }
    }
    if (!matched) {
      for (const [from, to] of SINGLE) {
        if (text.startsWith(from, i)) { res += to; i += from.length; matched = true; break; }
      }
    }
    if (!matched) { res += text[i]; i++; }
  }
  return res;
}

const T = {
  lotin: {
    /* ── Nav ── */
    nav_dashboard: "Bosh sahifa",
    nav_staff: "Xodimlar va Bo'limlar",
    nav_kpi_categories: "KPI Toifalari",
    nav_kpi_indicators: "KPI Ko'rsatkichlari",
    nav_evaluations: "Baholashlar",
    nav_work_plans: "Ish rejalari",
    nav_mfylar: "Hududlar",
    nav_settings: "Sozlamalar",
    nav_approve: "Tasdiqlash paneli",
    nav_admin: "Foydalanuvchilar",
    nav_logout: "Chiqish",
    nav_user: "Foydalanuvchi",
    nav_suv: "Suv Xo'jaligi",
    nav_kpi_system: "KPI Monitoring tizimi",
    /* ── Roles ── */
    role_admin: "Administrator",
    role_manager: "Menejer",
    role_employee: "Xodim",
    role_viewer: "Kuzatuvchi",
    /* ── Filters ── */
    filter_viloyat: "Viloyat",
    filter_tuman: "Tuman",
    filter_yil: "Yil",
    filter_oy: "Oy",
    filter_davr: "Davr",
    filter_all_viloyatlar: "Barcha viloyatlar",
    filter_all_tumanlar: "Barcha tumanlar",
    filter_select_viloyat: "— Viloyatni tanlang —",
    filter_select_tuman: "— Tumanni tanlang —",
    filter_all_depts: "Barcha bo'limlar",
    filter_all_statuses: "Barcha holatlar",
    filter_all_categories: "Barcha toifalar",
    filter_search_ph: "Qidirish...",
    /* ── Dashboard ── */
    dashboard_title: "Bosh sahifa",
    xlsx_download: ".xlsx yuklab olish",
    loading: "Yuklanmoqda...",
    no_data: "Ma'lumot yo'q",
    details: "Batafsil",
    wp_title: "Ish reja vazifalari holati",
    wp_total: "Jami vazifa",
    wp_completed: "Bajarildi",
    wp_in_progress: "Jarayonda",
    wp_pending: "Kutilmoqda",
    wp_rate: "Bajarilish darajasi",
    wp_tuman_col: "Tuman nomi",
    wp_dept_col: "Bo'lim nomi",
    wp_total_col: "Jami",
    wp_holat_col: "Holat",
    wp_executor: "Ijrochi",
    wp_co_executor_title: "Birgalikda bajaradigan ijrochilar KPI",
    wp_not_found: "Ish reja vazifalari topilmadi",
    card_employees: "Jami xodimlar",
    card_departments: "Bo'limlar soni",
    card_avg_score: "O'rtacha ball",
    card_total_eval: "Jami baholash",
    chart_top_employees: "Eng yaxshi xodimlar",
    chart_ball: "Ball",
    chart_dept_kpi: "Bo'limlar KPI",
    chart_dept_rating: "Bo'limlar reytingi",
    chart_top_results: "Top xodimlar natijasi",
    chart_trend: "KPI tendensiyasi",
    chart_rating: "Xodimlar reytingi",
    chart_monthly_trend: "Oylik trend",
    chart_score_axis: "Ball (0-100)",
    chart_avg_label: "O'rtacha",
    card_kpi_indicators: "KPI ko'rsatkichlari",
    welcome_subtitle: "Xush kelibsiz! Quyida tanlangan davr va hudud bo'yicha ma'lumotlar ko'rsatilgan.",
    selected_period_label: "Tanlangan davr",
    col_rank: "O'rin",
    col_name: "F.I.SH.",
    col_position: "Lavozim",
    col_dept: "Bo'lim",
    col_result: "Natija",
    recent_evals: "So'nggi baholashlar",
    col_employee: "Xodim",
    col_score: "Ball",
    col_date: "Sana",
    col_period: "Davr",
    col_unit: "O'lchov",
    col_target: "Maqsad",
    see_all: "Barchasini ko'rish",
    top10_title: "Eng yaxshi xodimlar (top 10)",
    wp_co_executor_col: "Ijrochi",
    no_data_found: "Ma'lumot topilmadi",
    yil_months_desc: "yil, oylar kesimida",
    davr_suffix: "davri",
    davr_top8: "davri, top 8 ta",
    davr_top10_desc: "davri bo'yicha eng yuqori natija",
    m1: "Yanvar", m2: "Fevral", m3: "Mart", m4: "Aprel",
    m5: "May", m6: "Iyun", m7: "Iyul", m8: "Avgust",
    m9: "Sentabr", m10: "Oktabr", m11: "Noyabr", m12: "Dekabr",
    davr_oylik: "Oylik",
    davr_q1: "1-chorak (Yan–Mar)",
    davr_q2: "2-chorak (Apr–Iyn)",
    davr_q3: "3-chorak (Iyl–Sen)",
    davr_q4: "4-chorak (Okt–Dek)",
    davr_h1: "1-yarim yillik",
    davr_h2: "2-yarim yillik",
    davr_yillik: "To'liq yil",
    lang_lotin: "Lotin",
    lang_kril: "Кирил",
    lang_rus: "Рус",
    /* ── Umumiy tugmalar ── */
    btn_add: "Qo'shish",
    btn_save: "Saqlash",
    btn_cancel: "Bekor qilish",
    btn_delete: "O'chirish",
    btn_edit: "Tahrirlash",
    btn_view: "Ko'rish",
    btn_clear: "Tozalash",
    btn_new: "Yangi",
    btn_logout: "Tizimdan chiqish",
    btn_saving: "Saqlanmoqda...",
    btn_deleting: "O'chirilmoqda...",
    btn_logout_pending: "Chiqilmoqda...",
    /* ── Status ── */
    status_active: "Faol",
    status_inactive: "Nofaol",
    status_draft: "Qoralama",
    status_submitted: "Yuborilgan",
    status_approved: "Tasdiqlangan",
    status_rejected: "Rad etilgan",
    status_completed: "Bajarilgan",
    status_pending: "Kutilmoqda",
    status_in_progress: "Jarayonda",
    status_all: "Hammasi",
    tab_work_plans: "Ish rejalari",
    tab_evaluations: "Baholashlar",
    btn_approve: "Tasdiqlash",
    btn_reject: "Rad etish",
    btn_reject_short: "Rad",
    btn_close: "Yopish",
    btn_excel: "Excel yuklab olish",
    btn_rejecting: "Rad etilmoqda...",
    lbl_actions: "Amallar",
    lbl_period: "Davr",
    lbl_status: "Holat",
    lbl_title: "Sarlavha",
    lbl_completion: "Bajarilish",
    lbl_tasks: "Vazifalar",
    lbl_employee_col: "Xodim",
    lbl_awaiting: "Imzosini kutmoqda...",
    lbl_not_approved_yet: "Tasdiqlanmagan",
    lbl_agreed: "Kelishildi",
    lbl_confirmed: "Tasdiqlandi",
    lbl_rejection_reason_prefix: "Rad sababi:",
    lbl_plan_tasks_table: "Chora-tadbirlar jadvali",
    lbl_no_tasks: "Hali vazifalar qo'shilmagan",
    lbl_completion_percent: "Bajarilishi",
    lbl_submitted_notice: "Bu ish reja imzolashga yuborilgan — tasdiqlanishi kutilmoqda.",
    lbl_plan_measures: "Chora-tadbirlar",
    lbl_mechanism: "Amalga oshirish mexanizmi",
    lbl_funding: "Moliyalashtirish manbalari",
    lbl_unit: "O'lchov birligi",
    lbl_planned: "Reja",
    lbl_actual: "Amalda",
    lbl_executor_col: "Birgalikda bajaradigan ijrochi",
    lbl_location_col: "Hudud",
    lbl_controller_col: "Tasdiqlovchi",
    lbl_view_pdf: "Ko'rish",
    lbl_work_plans_breadcrumb: "Ish rejalar",
    toast_approved: "Tasdiqlandi",
    toast_rejected: "Rad etildi",
    approve_reject_plan_title: "Ish rejani rad etish",
    approve_reject_eval_title: "Baholashni rad etish",
    approve_reject_reason_ph: "Rad etish sababi...",
    approve_reject_reason_opt: "rad etish sababi (ixtiyoriy)",
    approve_pending_none_plan: "Tasdiqlanishi kutilayotgan ish reja yo'q",
    approve_pending_none_eval: "Tasdiqlanishi kutilayotgan baholash yo'q",
    approve_region_attached: "Hududingizga biriktirilgan xodimlar",
    /* ── Jadval ustunlari ── */
    th_actions: "Amallar",
    th_head: "Rahbar",
    th_emp_count: "Xodimlar soni",
    th_indicator_count: "Ko'rsatkichlar soni",
    th_indicator: "Ko'rsatkich",
    th_weight: "Og'irlik",
    th_progress: "Bajarilish",
    th_tasks: "Vazifalar",
    th_title: "Sarlavha",
    th_status: "Holat",
    th_phone: "Telefon",
    th_email: "Email",
    th_tuman: "Tuman",
    th_category: "Toifa",
    th_name: "Nomi",
    th_code: "Kodi",
    th_description: "Tavsif",
    /* ── Bo'limlar / Xodimlar ── */
    lbl_departments: "Bo'limlar",
    lbl_employees: "Xodimlar",
    lbl_new_dept: "Yangi bo'lim",
    lbl_new_emp: "Yangi xodim",
    lbl_new_eval: "Yangi baholash",
    lbl_new_plan: "Yangi ish reja",
    lbl_new_category: "Yangi toifa",
    lbl_new_indicator: "Yangi ko'rsatkich",
    lbl_dept_org_desc: "Tashkilot tarkibidagi barcha bo'limlar",
    lbl_emp_in_dept: "Bo'limdagi xodimlar",
    lbl_people: "kishi",
    lbl_not_specified: "Ko'rsatilmagan",
    lbl_dept_not_found: "Bo'limlar topilmadi",
    lbl_emp_not_found: "Xodimlar topilmadi",
    lbl_eval_not_found: "Baholashlar topilmadi",
    lbl_plan_not_found: "Ish rejalari topilmadi",
    lbl_category_not_found: "Toifalar topilmadi",
    lbl_indicator_not_found: "Ko'rsatkichlar topilmadi",
    lbl_mfy_not_found: "MFY topilmadi",
    lbl_new_mfy: "Yangi MFY",
    lbl_tuman: "Tuman",
    lbl_total: "Jami",
    lbl_filtered: "tadan filtrlangan",
    delete_confirm_desc: "Bu amalni qaytarib bo'lmaydi. Ma'lumot bazadan butunlay o'chiriladi.",
    /* ── Forma yorliqlari ── */
    form_name: "Nomi",
    form_code: "Kodi",
    form_head_name: "Rahbar F.I.SH.",
    form_description: "Tavsif",
    form_full_name: "F.I.SH.",
    form_position: "Lavozim",
    form_dept: "Bo'lim",
    form_status: "Holat",
    form_phone: "Telefon",
    form_email: "Email",
    form_hire_date: "Ishga kirgan sana",
    form_tuman: "Tuman",
    form_login: "Login",
    form_password: "Parol",
    form_score: "Ball",
    form_comment: "Izoh",
    form_period: "Davr",
    form_indicator: "Ko'rsatkich",
    form_employee: "Xodim",
    form_title: "Sarlavha",
    form_category: "Toifa",
    form_weight: "Vazn",
    form_max_score: "Maks. ball",
    /* ── Dialoglar ── */
    dlg_delete_q: "O'chirishni tasdiqlaysizmi?",
    dlg_irreversible: "Bu amalni bekor qilib bo'lmaydi.",
    dlg_edit_dept: "Bo'limni tahrirlash",
    dlg_new_dept: "Yangi bo'lim qo'shish",
    dlg_edit_emp: "Xodimni tahrirlash",
    dlg_new_emp: "Yangi xodim qo'shish",
    dlg_edit_eval: "Baholashni tahrirlash",
    dlg_new_eval: "Yangi baholash qo'shish",
    dlg_edit_plan: "Ish rejani tahrirlash",
    dlg_edit_category: "Toifani tahrirlash",
    dlg_new_category: "Yangi toifa qo'shish",
    dlg_edit_indicator: "Ko'rsatkichni tahrirlash",
    dlg_new_indicator: "Yangi ko'rsatkich qo'shish",
    dlg_edit_mfy: "MFY tahrirlash",
    dlg_new_mfy: "Yangi MFY qo'shish",
    /* ── Toast xabarlari ── */
    toast_success: "Muvaffaqiyatli",
    toast_error: "Xatolik yuz berdi",
    toast_dept_added: "Bo'lim qo'shildi",
    toast_dept_updated: "Bo'lim yangilandi",
    toast_dept_deleted: "Bo'lim o'chirildi",
    toast_emp_added: "Xodim qo'shildi",
    toast_emp_updated: "Xodim ma'lumotlari yangilandi",
    toast_emp_deleted: "Xodim o'chirildi",
    toast_eval_added: "Baholash natijasi saqlandi",
    toast_eval_updated: "Baholash natijasi yangilandi",
    toast_eval_deleted: "Baholash natijasi o'chirildi",
    toast_plan_updated: "Ish reja yangilandi",
    toast_plan_deleted: "Ish reja o'chirildi",
    toast_cat_added: "Kategoriya qo'shildi",
    toast_cat_updated: "Kategoriya yangilandi",
    toast_cat_deleted: "Kategoriya o'chirildi",
    toast_ind_added: "Ko'rsatkich qo'shildi",
    toast_ind_updated: "Ko'rsatkich yangilandi",
    toast_ind_deleted: "Ko'rsatkich o'chirildi",
    toast_mfy_added: "MFY qo'shildi",
    toast_mfy_updated: "MFY yangilandi",
    toast_mfy_deleted: "MFY o'chirildi",
    /* ── Sahifa sarlavhalari ── */
    pg_staff: "Xodimlar va Bo'limlar",
    pg_staff_desc: "Tashkilot xodimlari va bo'limlari boshqaruvi",
    pg_evaluations: "Baholashlar",
    pg_evaluations_desc: "Xodimlarni oylik va davriy baholash natijalari",
    pg_work_plans: "Oylik ish rejalari",
    pg_work_plans_desc: "Xodimlarning oylik ish rejalari va ularning bajarilishi",
    pg_kpi_categories: "KPI Toifalari",
    pg_kpi_categories_desc: "Baholash toifalari va ularning umumiy vazni",
    pg_kpi_indicators: "KPI Ko'rsatkichlari",
    pg_kpi_indicators_desc: "Baholash mezonlari va ko'rsatkichlari",
    pg_settings: "Sozlamalar",
    pg_settings_desc: "Profil va tizim sozlamalari",
    settings_profile_title: "Profil ma'lumotlari",
    settings_profile_desc: "Sizning shaxsiy profilingiz",
    settings_dept_badge: "Bo'lim:",
    settings_username_label: "Foydalanuvchi nomi (Login)",
    settings_joined_label: "Tizimga ulanish sanasi",
    settings_security_title: "Xavfsizlik",
    settings_security_desc: "Sessiyani yakunlash",
    settings_logout_notice: "Tizimdan chiqish orqali joriy qurilmadagi sessiyangiz yakunlanadi.",
    pg_mfylar: "Hududlar",
    pg_mfylar_desc: "MFY va hududlarni boshqarish",
    pg_admin: "Foydalanuvchilar",
    pg_admin_desc: "Tizim foydalanuvchilari boshqaruvi",
    admin_page_title: "Foydalanuvchilar boshqaruvi",
    admin_page_desc: "Tizim foydalanuvchilarini qo'shish va boshqarish",
    admin_new_user: "Yangi foydalanuvchi",
    admin_filter_clear: "Tozalash",
    admin_all_regions: "— Barcha viloyatlar —",
    admin_all_districts: "— Barcha tumanlar —",
    admin_region_hint: "Tanlanmasa, foydalanuvchi barcha viloyat ma'lumotlarini ko'ra oladi",
    admin_district_hint: "Tuman tanlanmasa, butun viloyat ma'lumotlari ko'rsatiladi",
    admin_th_login: "Login",
    admin_th_fullname: "To'liq ismi",
    admin_th_role: "Rol",
    admin_th_region: "Viloyat / Tuman",
    admin_th_joined: "Qo'shilgan",
    admin_not_found: "Foydalanuvchilar topilmadi",
    admin_not_found_region: "Bu viloyatda foydalanuvchi topilmadi",
    admin_lbl_all_regions: "Barcha viloyatlar",
    admin_create_title: "Yangi foydalanuvchi qo'shish",
    admin_create_desc: "Tizimga kirish uchun hisob yarating.",
    admin_edit_title: "Foydalanuvchini tahrirlash",
    admin_delete_title: "Foydalanuvchini o'chirish",
    admin_delete_confirm_pre: "Haqiqatan ham",
    admin_delete_confirm_post: "ni o'chirmoqchimisiz?",
    admin_update_info: "ma'lumotlarini yangilang.",
    lbl_login_field: "Login",
    lbl_password: "Parol",
    lbl_fullname: "To'liq ismi",
    lbl_role: "Rol",
    lbl_new_password: "Yangi parol",
    lbl_optional: "(ixtiyoriy)",
    lbl_to_change: "(o'zgartirish uchun)",
    admin_adding: "Qo'shilmoqda...",
    toast_user_added: "Foydalanuvchi qo'shildi",
    toast_user_updated: "Yangilandi",
    toast_user_deleted: "Foydalanuvchi o'chirildi",
    lbl_viloyat: "Viloyat",
    lbl_tuman_optional: "Tuman",
    pg_approve: "Tasdiqlash paneli",
    pg_approve_desc: "Viloyat va tuman reytinglari",
    /* ── Tasdiqlash ── */
    approve_period: "Davr",
    approve_select_period: "Davrni tanlang",
    approve_viloyat_rating: "Viloyat reytingi",
    approve_tuman_rating: "Tuman reytingi",
    /* ── MFY ── */
    mfy_search_ph: "MFY nomi bo'yicha qidiring...",
    mfy_name_label: "MFY nomi",
    mfy_name_ph: "Masalan: Bog'bon MFY",
    mfy_tuman_label: "Tuman",
    /* ── Settings ── */
    settings_profile: "Profil ma'lumotlari",
    settings_logout: "Tizimdan chiqish",
  },
  kril: {
    /* ── Nav ── */
    nav_dashboard: "Бош саҳифа",
    nav_staff: "Ходимлар ва Бўлимлар",
    nav_kpi_categories: "КПИ Тоифалари",
    nav_kpi_indicators: "КПИ Кўрсаткичлари",
    nav_evaluations: "Баҳолашлар",
    nav_work_plans: "Иш режалари",
    nav_mfylar: "Ҳудудлар",
    nav_settings: "Созламалар",
    nav_approve: "Тасдиқлаш панели",
    nav_admin: "Фойдаланувчилар",
    nav_logout: "Чиқиш",
    nav_user: "Фойдаланувчи",
    nav_suv: "Сув Хўжалиги",
    nav_kpi_system: "КПИ Мониторинг тизими",
    /* ── Roles ── */
    role_admin: "Администратор",
    role_manager: "Менежер",
    role_employee: "Ходим",
    role_viewer: "Кузатувчи",
    /* ── Filters ── */
    filter_viloyat: "Вилоят",
    filter_tuman: "Туман",
    filter_yil: "Йил",
    filter_oy: "Ой",
    filter_davr: "Давр",
    filter_all_viloyatlar: "Барча вилоятлар",
    filter_all_tumanlar: "Барча туманлар",
    filter_select_viloyat: "— Вилоятни танланг —",
    filter_select_tuman: "— Туманни танланг —",
    filter_all_depts: "Барча бўлимлар",
    filter_all_statuses: "Барча ҳолатлар",
    filter_all_categories: "Барча тоифалар",
    filter_search_ph: "Қидириш...",
    /* ── Dashboard ── */
    dashboard_title: "Бош саҳифа",
    xlsx_download: ".xlsx юклаб олиш",
    loading: "Юкланмоқда...",
    no_data: "Маълумот йўқ",
    details: "Батафсил",
    wp_title: "Иш режа вазифалари ҳолати",
    wp_total: "Жами вазифа",
    wp_completed: "Бажарилди",
    wp_in_progress: "Жараёнда",
    wp_pending: "Кутилмоқда",
    wp_rate: "Бажарилиш даражаси",
    wp_tuman_col: "Туман номи",
    wp_dept_col: "Бўлим номи",
    wp_total_col: "Жами",
    wp_holat_col: "Ҳолат",
    wp_executor: "Ижрочи",
    wp_co_executor_title: "Биргаликда бажарадиган ижрочилар КПИ",
    wp_not_found: "Иш режа вазифалари топилмади",
    card_employees: "Жами ходимлар",
    card_departments: "Бўлимлар сони",
    card_avg_score: "Ўртача балл",
    card_total_eval: "Жами баҳолаш",
    chart_top_employees: "Энг яхши ходимлар",
    chart_ball: "Балл",
    chart_dept_kpi: "Бўлимлар КПИ",
    chart_dept_rating: "Бўлимлар рейтинги",
    chart_top_results: "Топ ходимлар натижаси",
    chart_trend: "КПИ тенденсияси",
    chart_rating: "Ходимлар рейтинги",
    chart_monthly_trend: "Ойлик тренд",
    chart_score_axis: "Балл (0-100)",
    chart_avg_label: "Ўртача",
    card_kpi_indicators: "КПИ кўрсаткичлари",
    welcome_subtitle: "Хуш келибсиз! Қуйида танланган давр ва ҳудуд бўйича маълумотлар кўрсатилган.",
    selected_period_label: "Танланган давр",
    col_rank: "Ўрин",
    col_name: "Ф.И.Ш.",
    col_position: "Лавозим",
    col_dept: "Бўлим",
    col_result: "Натижа",
    recent_evals: "Сўнги баҳолашлар",
    col_employee: "Ходим",
    col_score: "Балл",
    col_date: "Сана",
    col_period: "Давр",
    col_unit: "Ўлчов",
    col_target: "Мақсад",
    see_all: "Барчасини кўриш",
    top10_title: "Энг яхши ходимлар (топ 10)",
    wp_co_executor_col: "Ижрочи",
    no_data_found: "Маълумот топилмади",
    yil_months_desc: "йил, ойлар кесимида",
    davr_suffix: "даври",
    davr_top8: "даври, топ 8 та",
    davr_top10_desc: "даври бўйича энг юқори натижа",
    m1: "Январ", m2: "Феврал", m3: "Март", m4: "Апрел",
    m5: "Май", m6: "Июн", m7: "Июл", m8: "Август",
    m9: "Сентябр", m10: "Октябр", m11: "Ноябр", m12: "Декабр",
    davr_oylik: "Ойлик",
    davr_q1: "1-чорак (Янв–Мар)",
    davr_q2: "2-чорак (Апр–Июн)",
    davr_q3: "3-чорак (Июл–Сен)",
    davr_q4: "4-чорак (Окт–Дек)",
    davr_h1: "1-ярим йиллик",
    davr_h2: "2-ярим йиллик",
    davr_yillik: "Тўлиқ йил",
    lang_lotin: "Лотин",
    lang_kril: "Кирил",
    lang_rus: "Рус",
    /* ── Umumiy tugmalar ── */
    btn_add: "Қўшиш",
    btn_save: "Сақлаш",
    btn_cancel: "Бекор қилиш",
    btn_delete: "Ўчириш",
    btn_edit: "Таҳрирлаш",
    btn_view: "Кўриш",
    btn_clear: "Тозалаш",
    btn_new: "Янги",
    btn_logout: "Тизимдан чиқиш",
    btn_saving: "Сақланмоқда...",
    btn_deleting: "Ўчирилмоқда...",
    btn_logout_pending: "Чиқилмоқда...",
    /* ── Status ── */
    status_active: "Фаол",
    status_inactive: "Нофаол",
    status_draft: "Қоралама",
    status_submitted: "Юборилган",
    status_approved: "Тасдиқланган",
    status_rejected: "Рад этилган",
    status_completed: "Бажарилган",
    status_pending: "Кутилмоқда",
    status_in_progress: "Жараёнда",
    status_all: "Ҳаммаси",
    tab_work_plans: "Иш режалари",
    tab_evaluations: "Баҳолашлар",
    btn_approve: "Тасдиқлаш",
    btn_reject: "Рад этиш",
    btn_reject_short: "Рад",
    btn_close: "Ёпиш",
    btn_excel: "Excel юклаб олиш",
    btn_rejecting: "Рад этилмоқда...",
    lbl_actions: "Амаллар",
    lbl_period: "Давр",
    lbl_status: "Ҳолат",
    lbl_title: "Сарлавҳа",
    lbl_completion: "Бажарилиш",
    lbl_tasks: "Вазифалар",
    lbl_employee_col: "Ходим",
    lbl_awaiting: "Имзосини кутмоқда...",
    lbl_not_approved_yet: "Тасдиқланмаган",
    lbl_agreed: "Келишилди",
    lbl_confirmed: "Тасдиқланди",
    lbl_rejection_reason_prefix: "Рад сабаби:",
    lbl_plan_tasks_table: "Чора-тадбирлар жадвали",
    lbl_no_tasks: "Ҳали вазифалар қўшилмаган",
    lbl_completion_percent: "Бажарилиши",
    lbl_submitted_notice: "Бу иш режа имзолашга юборилган — тасдиқланиши кутилмоқда.",
    lbl_plan_measures: "Чора-тадбирлар",
    lbl_mechanism: "Амалга ошириш механизми",
    lbl_funding: "Молиялаштириш манбалари",
    lbl_unit: "Ўлчов бирлиги",
    lbl_planned: "Режа",
    lbl_actual: "Амалда",
    lbl_executor_col: "Биргаликда бажарадиган ижрочи",
    lbl_location_col: "Ҳудуд",
    lbl_controller_col: "Тасдиқловчи",
    lbl_view_pdf: "Кўриш",
    lbl_work_plans_breadcrumb: "Иш режалар",
    toast_approved: "Тасдиқланди",
    toast_rejected: "Рад этилди",
    approve_reject_plan_title: "Иш режани рад этиш",
    approve_reject_eval_title: "Баҳолашни рад этиш",
    approve_reject_reason_ph: "Рад этиш сабаби...",
    approve_reject_reason_opt: "рад этиш сабаби (ихтиёрий)",
    approve_pending_none_plan: "Тасдиқланиши кутилаётган иш режа йўқ",
    approve_pending_none_eval: "Тасдиқланиши кутилаётган баҳолаш йўқ",
    approve_region_attached: "Ҳудудингизга бириктирилган ходимлар",
    /* ── Jadval ustunlari ── */
    th_actions: "Амаллар",
    th_head: "Раҳбар",
    th_emp_count: "Ходимлар сони",
    th_indicator_count: "Кўрсаткичлар сони",
    th_indicator: "Кўрсаткич",
    th_weight: "Оғирлик",
    th_progress: "Бажарилиш",
    th_tasks: "Вазифалар",
    th_title: "Сарлавҳа",
    th_status: "Ҳолат",
    th_phone: "Телефон",
    th_email: "Email",
    th_tuman: "Туман",
    th_category: "Тоифа",
    th_name: "Номи",
    th_code: "Коди",
    th_description: "Тавсиф",
    /* ── Bo'limlar / Xodimlar ── */
    lbl_departments: "Бўлимлар",
    lbl_employees: "Ходимлар",
    lbl_new_dept: "Янги бўлим",
    lbl_new_emp: "Янги ходим",
    lbl_new_eval: "Янги баҳолаш",
    lbl_new_plan: "Янги иш режа",
    lbl_new_category: "Янги тоифа",
    lbl_new_indicator: "Янги кўрсаткич",
    lbl_dept_org_desc: "Ташкилот таркибидаги барча бўлимлар",
    lbl_emp_in_dept: "Бўлимдаги ходимлар",
    lbl_people: "киши",
    lbl_not_specified: "Кўрсатилмаган",
    lbl_dept_not_found: "Бўлимлар топилмади",
    lbl_emp_not_found: "Ходимлар топилмади",
    lbl_eval_not_found: "Баҳолашлар топилмади",
    lbl_plan_not_found: "Иш режалари топилмади",
    lbl_category_not_found: "Тоифалар топилмади",
    lbl_indicator_not_found: "Кўрсаткичлар топилмади",
    lbl_mfy_not_found: "МФЙ топилмади",
    lbl_new_mfy: "Янги МФЙ",
    lbl_tuman: "Туман",
    lbl_total: "Жами",
    lbl_filtered: "тадан филтрланган",
    delete_confirm_desc: "Бу амални қайтариб бўлмайди. Маълумот базадан бутунлай ўчирилади.",
    /* ── Forma yorliqlari ── */
    form_name: "Номи",
    form_code: "Коди",
    form_head_name: "Раҳбар Ф.И.Ш.",
    form_description: "Тавсиф",
    form_full_name: "Ф.И.Ш.",
    form_position: "Лавозим",
    form_dept: "Бўлим",
    form_status: "Ҳолат",
    form_phone: "Телефон",
    form_email: "Email",
    form_hire_date: "Ишга кирган сана",
    form_tuman: "Туман",
    form_login: "Логин",
    form_password: "Парол",
    form_score: "Балл",
    form_comment: "Изоҳ",
    form_period: "Давр",
    form_indicator: "Кўрсаткич",
    form_employee: "Ходим",
    form_title: "Сарлавҳа",
    form_category: "Тоифа",
    form_weight: "Вазн",
    form_max_score: "Макс. балл",
    /* ── Dialoglar ── */
    dlg_delete_q: "Ўчиришни тасдиқлайсизми?",
    dlg_irreversible: "Бу амални бекор қилиб бўлмайди.",
    dlg_edit_dept: "Бўлимни таҳрирлаш",
    dlg_new_dept: "Янги бўлим қўшиш",
    dlg_edit_emp: "Ходимни таҳрирлаш",
    dlg_new_emp: "Янги ходим қўшиш",
    dlg_edit_eval: "Баҳолашни таҳрирлаш",
    dlg_new_eval: "Янги баҳолаш қўшиш",
    dlg_edit_plan: "Иш режани таҳрирлаш",
    dlg_edit_category: "Тоифани таҳрирлаш",
    dlg_new_category: "Янги тоифа қўшиш",
    dlg_edit_indicator: "Кўрсаткични таҳрирлаш",
    dlg_new_indicator: "Янги кўрсаткич қўшиш",
    dlg_edit_mfy: "МФЙ таҳрирлаш",
    dlg_new_mfy: "Янги МФЙ қўшиш",
    /* ── Toast xabarlari ── */
    toast_success: "Муваффақиятли",
    toast_error: "Хатолик юз берди",
    toast_dept_added: "Бўлим қўшилди",
    toast_dept_updated: "Бўлим янгиланди",
    toast_dept_deleted: "Бўлим ўчирилди",
    toast_emp_added: "Ходим қўшилди",
    toast_emp_updated: "Ходим маълумотлари янгиланди",
    toast_emp_deleted: "Ходим ўчирилди",
    toast_eval_added: "Баҳолаш натижаси сақланди",
    toast_eval_updated: "Баҳолаш натижаси янгиланди",
    toast_eval_deleted: "Баҳолаш натижаси ўчирилди",
    toast_plan_updated: "Иш режа янгиланди",
    toast_plan_deleted: "Иш режа ўчирилди",
    toast_cat_added: "Категория қўшилди",
    toast_cat_updated: "Категория янгиланди",
    toast_cat_deleted: "Категория ўчирилди",
    toast_ind_added: "Кўрсаткич қўшилди",
    toast_ind_updated: "Кўрсаткич янгиланди",
    toast_ind_deleted: "Кўрсаткич ўчирилди",
    toast_mfy_added: "МФЙ қўшилди",
    toast_mfy_updated: "МФЙ янгиланди",
    toast_mfy_deleted: "МФЙ ўчирилди",
    /* ── Sahifa sarlavhalari ── */
    pg_staff: "Ходимлар ва Бўлимлар",
    pg_staff_desc: "Ташкилот ходимлари ва бўлимлари бошқаруви",
    pg_evaluations: "Баҳолашлар",
    pg_evaluations_desc: "Ходимларни ойлик ва даврий баҳолаш натижалари",
    pg_work_plans: "Ойлик иш режалари",
    pg_work_plans_desc: "Ходимларнинг ойлик иш режалари ва уларнинг бажарилиши",
    pg_kpi_categories: "КПИ Тоифалари",
    pg_kpi_categories_desc: "Баҳолаш тоифалари ва уларнинг умумий вазни",
    pg_kpi_indicators: "КПИ Кўрсаткичлари",
    pg_kpi_indicators_desc: "Баҳолаш мезонлари ва кўрсаткичлари",
    pg_settings: "Созламалар",
    pg_settings_desc: "Профил ва тизим созламалари",
    settings_profile_title: "Профил маълумотлари",
    settings_profile_desc: "Сизнинг шахсий профилингиз",
    settings_dept_badge: "Бўлим:",
    settings_username_label: "Фойдаланувчи номи (Логин)",
    settings_joined_label: "Тизимга уланиш санаси",
    settings_security_title: "Хавфсизлик",
    settings_security_desc: "Сессияни якунлаш",
    settings_logout_notice: "Тизимдан чиқиш орқали жорий қурилмадаги сессиянгиз якунланади.",
    pg_mfylar: "Ҳудудлар",
    pg_mfylar_desc: "МФЙ ва ҳудудларни бошқариш",
    pg_admin: "Фойдаланувчилар",
    pg_admin_desc: "Тизим фойдаланувчилари бошқаруви",
    admin_page_title: "Фойдаланувчилар бошқаруви",
    admin_page_desc: "Тизим фойдаланувчиларини қўшиш ва бошқариш",
    admin_new_user: "Янги фойдаланувчи",
    admin_filter_clear: "Тозалаш",
    admin_all_regions: "— Барча вилоятлар —",
    admin_all_districts: "— Барча туманлар —",
    admin_region_hint: "Танланмаса, фойдаланувчи барча вилоят маълумотларини кўра олади",
    admin_district_hint: "Туман танланмаса, бутун вилоят маълумотлари кўрсатилади",
    admin_th_login: "Логин",
    admin_th_fullname: "Тўлиқ исми",
    admin_th_role: "Рол",
    admin_th_region: "Вилоят / Туман",
    admin_th_joined: "Қўшилган",
    admin_not_found: "Фойдаланувчилар топилмади",
    admin_not_found_region: "Бу вилоятда фойдаланувчи топилмади",
    admin_lbl_all_regions: "Барча вилоятлар",
    admin_create_title: "Янги фойдаланувчи қўшиш",
    admin_create_desc: "Тизимга кириш учун ҳисоб яратинг.",
    admin_edit_title: "Фойдаланувчини таҳрирлаш",
    admin_delete_title: "Фойдаланувчини ўчириш",
    admin_delete_confirm_pre: "Ҳақиқатан ҳам",
    admin_delete_confirm_post: "ни ўчирмоқчимисиз?",
    admin_update_info: "маълумотларини янгиланг.",
    lbl_login_field: "Логин",
    lbl_password: "Парол",
    lbl_fullname: "Тўлиқ исми",
    lbl_role: "Рол",
    lbl_new_password: "Янги парол",
    lbl_optional: "(ихтиёрий)",
    lbl_to_change: "(ўзгартириш учун)",
    admin_adding: "Қўшилмоқда...",
    toast_user_added: "Фойдаланувчи қўшилди",
    toast_user_updated: "Янгиланди",
    toast_user_deleted: "Фойдаланувчи ўчирилди",
    lbl_viloyat: "Вилоят",
    lbl_tuman_optional: "Туман",
    pg_approve: "Тасдиқлаш панели",
    pg_approve_desc: "Вилоят ва туман рейтинглари",
    /* ── Tasdiqlash ── */
    approve_period: "Давр",
    approve_select_period: "Даврни танланг",
    approve_viloyat_rating: "Вилоят рейтинги",
    approve_tuman_rating: "Туман рейтинги",
    /* ── MFY ── */
    mfy_search_ph: "МФЙ номи бўйича қидиринг...",
    mfy_name_label: "МФЙ номи",
    mfy_name_ph: "Масалан: Боғбон МФЙ",
    mfy_tuman_label: "Туман",
    /* ── Settings ── */
    settings_profile: "Профил маълумотлари",
    settings_logout: "Тизимдан чиқиш",
  },
  rus: {
    /* ── Nav ── */
    nav_dashboard: "Главная",
    nav_staff: "Сотрудники и отделы",
    nav_kpi_categories: "Категории KPI",
    nav_kpi_indicators: "Показатели KPI",
    nav_evaluations: "Оценки",
    nav_work_plans: "Рабочие планы",
    nav_mfylar: "Территории",
    nav_settings: "Настройки",
    nav_approve: "Панель утверждения",
    nav_admin: "Пользователи",
    nav_logout: "Выход",
    nav_user: "Пользователь",
    nav_suv: "Водное хозяйство",
    nav_kpi_system: "Система мониторинга KPI",
    /* ── Roles ── */
    role_admin: "Администратор",
    role_manager: "Менеджер",
    role_employee: "Сотрудник",
    role_viewer: "Наблюдатель",
    /* ── Filters ── */
    filter_viloyat: "Область",
    filter_tuman: "Район",
    filter_yil: "Год",
    filter_oy: "Месяц",
    filter_davr: "Период",
    filter_all_viloyatlar: "Все регионы",
    filter_all_tumanlar: "Все районы",
    filter_select_viloyat: "— Выберите регион —",
    filter_select_tuman: "— Выберите район —",
    filter_all_depts: "Все отделы",
    filter_all_statuses: "Все статусы",
    filter_all_categories: "Все категории",
    filter_search_ph: "Поиск...",
    /* ── Dashboard ── */
    dashboard_title: "Главная",
    xlsx_download: "Скачать .xlsx",
    loading: "Загрузка...",
    no_data: "Нет данных",
    details: "Подробнее",
    wp_title: "Статус задач рабочего плана",
    wp_total: "Всего задач",
    wp_completed: "Выполнено",
    wp_in_progress: "В процессе",
    wp_pending: "Ожидается",
    wp_rate: "Степень выполнения",
    wp_tuman_col: "Название района",
    wp_dept_col: "Название отдела",
    wp_total_col: "Всего",
    wp_holat_col: "Состояние",
    wp_executor: "Исполнитель",
    wp_co_executor_title: "KPI совместных исполнителей",
    wp_not_found: "Задачи рабочего плана не найдены",
    card_employees: "Всего сотрудников",
    card_departments: "Количество отделов",
    card_avg_score: "Средний балл",
    card_total_eval: "Всего оценок",
    chart_top_employees: "Лучшие сотрудники",
    chart_ball: "Балл",
    chart_dept_kpi: "KPI отделов",
    chart_dept_rating: "Рейтинг отделов",
    chart_top_results: "Топ сотрудников",
    chart_trend: "Тенденция KPI",
    chart_rating: "Рейтинг сотрудников",
    chart_monthly_trend: "Ежемесячный тренд",
    chart_score_axis: "Балл (0-100)",
    chart_avg_label: "Среднее",
    card_kpi_indicators: "Показатели KPI",
    welcome_subtitle: "Добро пожаловать! Ниже показаны данные за выбранный период и регион.",
    selected_period_label: "Выбранный период",
    recent_evals: "Последние оценки",
    col_rank: "Место",
    col_name: "Ф.И.О.",
    col_position: "Должность",
    col_dept: "Отдел",
    col_result: "Результат",
    col_employee: "Сотрудник",
    col_score: "Балл",
    col_date: "Дата",
    col_period: "Период",
    col_unit: "Единица",
    col_target: "Цель",
    see_all: "Посмотреть все",
    top10_title: "Лучшие сотрудники (топ 10)",
    wp_co_executor_col: "Исполнитель",
    no_data_found: "Данные не найдены",
    yil_months_desc: "год, по месяцам",
    davr_suffix: "периода",
    davr_top8: "период, топ 8",
    davr_top10_desc: "период, наивысший результат",
    m1: "Январь", m2: "Февраль", m3: "Март", m4: "Апрель",
    m5: "Май", m6: "Июнь", m7: "Июль", m8: "Август",
    m9: "Сентябрь", m10: "Октябрь", m11: "Ноябрь", m12: "Декабрь",
    davr_oylik: "Ежемесячно",
    davr_q1: "1-й квартал (Янв–Мар)",
    davr_q2: "2-й квартал (Апр–Июн)",
    davr_q3: "3-й квартал (Июл–Сен)",
    davr_q4: "4-й квартал (Окт–Дек)",
    davr_h1: "1-е полугодие",
    davr_h2: "2-е полугодие",
    davr_yillik: "Полный год",
    lang_lotin: "Латин",
    lang_kril: "Кирилл",
    lang_rus: "Русский",
    /* ── Umumiy tugmalar ── */
    btn_add: "Добавить",
    btn_save: "Сохранить",
    btn_cancel: "Отмена",
    btn_delete: "Удалить",
    btn_edit: "Редактировать",
    btn_view: "Просмотр",
    btn_clear: "Очистить",
    btn_new: "Новый",
    btn_logout: "Выйти из системы",
    btn_saving: "Сохраняется...",
    btn_deleting: "Удаляется...",
    btn_logout_pending: "Выходим...",
    /* ── Status ── */
    status_active: "Активный",
    status_inactive: "Неактивный",
    status_draft: "Черновик",
    status_submitted: "Отправлен",
    status_approved: "Утверждён",
    status_rejected: "Отклонён",
    status_completed: "Выполнен",
    status_pending: "Ожидается",
    status_in_progress: "В процессе",
    status_all: "Все",
    tab_work_plans: "Рабочие планы",
    tab_evaluations: "Оценки",
    btn_approve: "Утвердить",
    btn_reject: "Отклонить",
    btn_reject_short: "Откл.",
    btn_close: "Закрыть",
    btn_excel: "Скачать Excel",
    btn_rejecting: "Отклоняется...",
    lbl_actions: "Действия",
    lbl_period: "Период",
    lbl_status: "Статус",
    lbl_title: "Заголовок",
    lbl_completion: "Выполнение",
    lbl_tasks: "Задачи",
    lbl_employee_col: "Сотрудник",
    lbl_awaiting: "Ожидание подписи...",
    lbl_not_approved_yet: "Не утверждено",
    lbl_agreed: "Согласовано",
    lbl_confirmed: "Утверждено",
    lbl_rejection_reason_prefix: "Причина отказа:",
    lbl_plan_tasks_table: "Таблица мероприятий",
    lbl_no_tasks: "Задачи ещё не добавлены",
    lbl_completion_percent: "Выполнение",
    lbl_submitted_notice: "Этот рабочий план отправлен на подпись — ожидается утверждение.",
    lbl_plan_measures: "Мероприятия",
    lbl_mechanism: "Механизм реализации",
    lbl_funding: "Источники финансирования",
    lbl_unit: "Единица измерения",
    lbl_planned: "План",
    lbl_actual: "Факт",
    lbl_executor_col: "Соисполнитель",
    lbl_location_col: "Территория",
    lbl_controller_col: "Утверждающий",
    lbl_view_pdf: "Просмотр",
    lbl_work_plans_breadcrumb: "Рабочие планы",
    toast_approved: "Утверждено",
    toast_rejected: "Отклонено",
    approve_reject_plan_title: "Отклонить рабочий план",
    approve_reject_eval_title: "Отклонить оценку",
    approve_reject_reason_ph: "Причина отказа...",
    approve_reject_reason_opt: "причина отказа (необязательно)",
    approve_pending_none_plan: "Нет рабочих планов, ожидающих утверждения",
    approve_pending_none_eval: "Нет оценок, ожидающих утверждения",
    approve_region_attached: "Сотрудники, прикреплённые к вашему региону",
    /* ── Jadval ustunlari ── */
    th_actions: "Действия",
    th_head: "Руководитель",
    th_emp_count: "Кол-во сотр.",
    th_indicator_count: "Кол-во показателей",
    th_indicator: "Показатель",
    th_weight: "Вес",
    th_progress: "Выполнение",
    th_tasks: "Задачи",
    th_title: "Заголовок",
    th_status: "Статус",
    th_phone: "Телефон",
    th_email: "Email",
    th_tuman: "Район",
    th_category: "Категория",
    th_name: "Название",
    th_code: "Код",
    th_description: "Описание",
    /* ── Bo'limlar / Xodimlar ── */
    lbl_departments: "Отделы",
    lbl_employees: "Сотрудники",
    lbl_new_dept: "Новый отдел",
    lbl_new_emp: "Новый сотрудник",
    lbl_new_eval: "Новая оценка",
    lbl_new_plan: "Новый рабочий план",
    lbl_new_category: "Новая категория",
    lbl_new_indicator: "Новый показатель",
    lbl_dept_org_desc: "Все отделы в составе организации",
    lbl_emp_in_dept: "Сотрудники отдела",
    lbl_people: "чел.",
    lbl_not_specified: "Не указано",
    lbl_dept_not_found: "Отделы не найдены",
    lbl_emp_not_found: "Сотрудники не найдены",
    lbl_eval_not_found: "Оценки не найдены",
    lbl_plan_not_found: "Рабочие планы не найдены",
    lbl_category_not_found: "Категории не найдены",
    lbl_indicator_not_found: "Показатели не найдены",
    lbl_mfy_not_found: "МФЙ не найдены",
    lbl_new_mfy: "Новый МФЙ",
    lbl_tuman: "Район",
    lbl_total: "Итого",
    lbl_filtered: "отфильтровано из",
    delete_confirm_desc: "Это действие нельзя отменить. Запись будет удалена из базы данных.",
    /* ── Forma yorliqlari ── */
    form_name: "Название",
    form_code: "Код",
    form_head_name: "Ф.И.О. руководителя",
    form_description: "Описание",
    form_full_name: "Ф.И.О.",
    form_position: "Должность",
    form_dept: "Отдел",
    form_status: "Статус",
    form_phone: "Телефон",
    form_email: "Email",
    form_hire_date: "Дата приёма",
    form_tuman: "Район",
    form_login: "Логин",
    form_password: "Пароль",
    form_score: "Балл",
    form_comment: "Комментарий",
    form_period: "Период",
    form_indicator: "Показатель",
    form_employee: "Сотрудник",
    form_title: "Заголовок",
    form_category: "Категория",
    form_weight: "Вес",
    form_max_score: "Макс. балл",
    /* ── Dialoglar ── */
    dlg_delete_q: "Подтвердите удаление",
    dlg_irreversible: "Это действие нельзя отменить.",
    dlg_edit_dept: "Редактировать отдел",
    dlg_new_dept: "Добавить новый отдел",
    dlg_edit_emp: "Редактировать сотрудника",
    dlg_new_emp: "Добавить нового сотрудника",
    dlg_edit_eval: "Редактировать оценку",
    dlg_new_eval: "Добавить новую оценку",
    dlg_edit_plan: "Редактировать рабочий план",
    dlg_edit_category: "Редактировать категорию",
    dlg_new_category: "Добавить новую категорию",
    dlg_edit_indicator: "Редактировать показатель",
    dlg_new_indicator: "Добавить новый показатель",
    dlg_edit_mfy: "Редактировать МФЙ",
    dlg_new_mfy: "Добавить новый МФЙ",
    /* ── Toast xabarlari ── */
    toast_success: "Успешно",
    toast_error: "Произошла ошибка",
    toast_dept_added: "Отдел добавлен",
    toast_dept_updated: "Отдел обновлён",
    toast_dept_deleted: "Отдел удалён",
    toast_emp_added: "Сотрудник добавлен",
    toast_emp_updated: "Данные сотрудника обновлены",
    toast_emp_deleted: "Сотрудник удалён",
    toast_eval_added: "Оценка сохранена",
    toast_eval_updated: "Оценка обновлена",
    toast_eval_deleted: "Оценка удалена",
    toast_plan_updated: "Рабочий план обновлён",
    toast_plan_deleted: "Рабочий план удалён",
    toast_cat_added: "Категория добавлена",
    toast_cat_updated: "Категория обновлена",
    toast_cat_deleted: "Категория удалена",
    toast_ind_added: "Показатель добавлен",
    toast_ind_updated: "Показатель обновлён",
    toast_ind_deleted: "Показатель удалён",
    toast_mfy_added: "МФЙ добавлен",
    toast_mfy_updated: "МФЙ обновлён",
    toast_mfy_deleted: "МФЙ удалён",
    /* ── Sahifa sarlavhalari ── */
    pg_staff: "Сотрудники и отделы",
    pg_staff_desc: "Управление сотрудниками и отделами организации",
    pg_evaluations: "Оценки",
    pg_evaluations_desc: "Результаты ежемесячной и периодической оценки сотрудников",
    pg_work_plans: "Ежемесячные рабочие планы",
    pg_work_plans_desc: "Ежемесячные рабочие планы сотрудников и их выполнение",
    pg_kpi_categories: "Категории KPI",
    pg_kpi_categories_desc: "Категории оценки и их общий вес",
    pg_kpi_indicators: "Показатели KPI",
    pg_kpi_indicators_desc: "Критерии и показатели оценки",
    pg_settings: "Настройки",
    pg_settings_desc: "Профиль и настройки системы",
    settings_profile_title: "Данные профиля",
    settings_profile_desc: "Ваш личный профиль",
    settings_dept_badge: "Отдел:",
    settings_username_label: "Имя пользователя (Логин)",
    settings_joined_label: "Дата регистрации",
    settings_security_title: "Безопасность",
    settings_security_desc: "Завершение сессии",
    settings_logout_notice: "При выходе из системы текущая сессия на этом устройстве будет завершена.",
    pg_mfylar: "Территории",
    pg_mfylar_desc: "Управление МФЙ и территориями",
    pg_admin: "Пользователи",
    pg_admin_desc: "Управление пользователями системы",
    admin_page_title: "Управление пользователями",
    admin_page_desc: "Добавление и управление пользователями системы",
    admin_new_user: "Новый пользователь",
    admin_filter_clear: "Очистить",
    admin_all_regions: "— Все регионы —",
    admin_all_districts: "— Все районы —",
    admin_region_hint: "Если не выбрано, пользователь видит данные всех регионов",
    admin_district_hint: "Если район не выбран, отображаются данные всего региона",
    admin_th_login: "Логин",
    admin_th_fullname: "Полное имя",
    admin_th_role: "Роль",
    admin_th_region: "Регион / Район",
    admin_th_joined: "Добавлен",
    admin_not_found: "Пользователи не найдены",
    admin_not_found_region: "В этом регионе пользователи не найдены",
    admin_lbl_all_regions: "Все регионы",
    admin_create_title: "Добавить нового пользователя",
    admin_create_desc: "Создайте учётную запись для входа в систему.",
    admin_edit_title: "Редактировать пользователя",
    admin_delete_title: "Удалить пользователя",
    admin_delete_confirm_pre: "Вы действительно хотите удалить",
    admin_delete_confirm_post: "?",
    admin_update_info: "Обновите данные пользователя.",
    lbl_login_field: "Логин",
    lbl_password: "Пароль",
    lbl_fullname: "Полное имя",
    lbl_role: "Роль",
    lbl_new_password: "Новый пароль",
    lbl_optional: "(необязательно)",
    lbl_to_change: "(для изменения)",
    admin_adding: "Добавление...",
    toast_user_added: "Пользователь добавлен",
    toast_user_updated: "Обновлено",
    toast_user_deleted: "Пользователь удалён",
    lbl_viloyat: "Регион",
    lbl_tuman_optional: "Район",
    pg_approve: "Панель утверждения",
    pg_approve_desc: "Рейтинги областей и районов",
    /* ── Tasdiqlash ── */
    approve_period: "Период",
    approve_select_period: "Выберите период",
    approve_viloyat_rating: "Рейтинг областей",
    approve_tuman_rating: "Рейтинг районов",
    /* ── MFY ── */
    mfy_search_ph: "Поиск по названию МФЙ...",
    mfy_name_label: "Название МФЙ",
    mfy_name_ph: "Например: МФЙ Богбон",
    mfy_tuman_label: "Район",
    /* ── Settings ── */
    settings_profile: "Данные профиля",
    settings_logout: "Выйти из системы",
  },
} as const;

export type TranslationKey = keyof typeof T.lotin;

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
  translit: (text: string) => string;
  /** Ma'lumotlar bazasidan kelgan matnni joriy tilga moslaydi */
  d: (text?: string | null) => string;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem(LANG_KEY);
    if (saved === "lotin" || saved === "kril" || saved === "rus") return saved;
    return "lotin";
  });

  const setLang = (l: Lang) => {
    localStorage.setItem(LANG_KEY, l);
    setLangState(l);
  };

  const t = (key: TranslationKey): string => T[lang][key] as string;

  const translit = (text: string): string => {
    if (lang === "kril") return translitToKril(text);
    return text;
  };

  /** Kirilcha matnni lotin tilida ko'rsatish uchun */
  const d = (text?: string | null): string => {
    if (!text) return "";
    if (lang === "lotin") return cyrToLatin(text);
    return text;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, translit, d }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
